@extends('backend.layouts.app')
@section('title', 'Vouchers | Cholavin ERP')
@section('content')
<div id="vouchers-module" data-index-url="{{ route('admin.vouchers.index') }}" data-pdf-url="{{ route('admin.vouchers.pdf') }}" data-payment-url="{{ route('admin.payments.index') }}" data-finance-url="{{ route('admin.financial-overview') }}">
    <div class="card erp-panel mb-3"><div class="card-body d-flex flex-wrap justify-content-between align-items-center gap-3"><div><span class="erp-eyebrow">Double-entry accounting</span><h4 class="mb-1">Journal Vouchers</h4><p class="text-muted mb-0">Balanced debit-credit posting with export, audit-ready references, and finance shortcuts.</p></div><div class="d-flex flex-wrap gap-2">@can('accounts.export')<button id="vouchers-pdf" class="btn btn-secondary" type="button"><i class="ri-file-pdf-2-line me-1"></i>PDF</button>@endcan @can('accounts.create')<button id="add-voucher" class="btn btn-primary" type="button"><i class="ri-add-circle-line me-1"></i>New Voucher</button>@endcan</div></div></div>
    <div class="accordion mb-3" id="voucher-filter-accordion"><div class="accordion-item erp-panel"><h2 class="accordion-header"><button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#voucher-filter-panel"><i class="ri-filter-3-line me-2"></i>Filters</button></h2><div id="voucher-filter-panel" class="accordion-collapse collapse" data-bs-parent="#voucher-filter-accordion"><div class="accordion-body"><form id="voucher-filters" class="row g-3">
        <div class="col-lg-3"><label class="form-label" for="voucher-search">Search</label><input id="voucher-search" class="form-control" type="search" placeholder="Number or reference"></div><div class="col-lg-3"><label class="form-label" for="voucher-type-filter">Type</label><select id="voucher-type-filter" class="form-select"><option value="">All</option>@foreach(['journal','contra','expense','income','opening'] as $type)<option value="{{ $type }}">{{ ucfirst($type) }}</option>@endforeach</select></div><div class="col-lg-2"><label class="form-label" for="voucher-from-filter">From</label><input id="voucher-from-filter" type="date" class="form-control"></div><div class="col-lg-2"><label class="form-label" for="voucher-to-filter">To</label><input id="voucher-to-filter" type="date" class="form-control"></div><div class="col-lg-2 align-self-end"><button id="reset-voucher-filters" class="btn btn-secondary w-100" type="button">Reset</button></div>
    </form></div></div></div></div>
    <div class="card erp-panel"><div class="card-body table-responsive"><table id="vouchers-table" class="table table-hover align-middle w-100"><thead><tr><th>S.No</th><th>Number</th><th>Date</th><th>Type</th><th>Reference</th><th>Lines</th><th>Total</th><th>Actions</th></tr></thead></table></div></div>
    <div id="voucher-modal" class="modal fade erp-form-modal" tabindex="-1" aria-labelledby="voucher-modal-title" aria-hidden="true"><div class="modal-dialog modal-dialog-centered modal-dialog-scrollable modal-xl modal-fullscreen-sm-down"><div class="modal-content"><div class="modal-header"><div><span class="erp-eyebrow">Double-entry accounting</span><h5 id="voucher-modal-title" class="modal-title">Balanced Voucher</h5></div><button class="btn-close" type="button" data-bs-dismiss="modal" aria-label="Close"></button></div><form id="voucher-form" action="{{ route('admin.vouchers.store') }}" method="POST" novalidate>@csrf<div class="modal-body">
        <div class="row g-3 mb-3"><div class="col-md-4 form-group"><label class="form-label">Type</label><select name="type" class="form-select">@foreach(['journal','contra','expense','income','opening'] as $type)<option value="{{ $type }}">{{ ucfirst($type) }}</option>@endforeach</select></div><div class="col-md-4 form-group"><label class="form-label">Date</label><input name="voucher_date" type="date" value="{{ now()->toDateString() }}" class="form-control"></div><div class="col-md-4 form-group"><label class="form-label">Reference</label><input name="reference_number" class="form-control"></div></div>
        <div class="d-flex justify-content-between align-items-center mb-2"><h6 class="mb-0">Voucher lines</h6><button id="add-voucher-line" class="btn btn-sm btn-secondary" type="button"><i class="ri-add-line me-1"></i>Add line</button></div><div id="voucher-lines"></div>
        <div class="alert alert-light border d-flex justify-content-between"><span>Debit: <strong id="voucher-debit-total">0.00</strong></span><span>Credit: <strong id="voucher-credit-total">0.00</strong></span><span>Difference: <strong id="voucher-difference">0.00</strong></span></div>
        <div class="form-group"><label class="form-label">Narration</label><textarea name="narration" class="form-control" rows="3"></textarea></div>
    </div><div class="modal-footer"><button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button><button type="submit" class="btn btn-primary">Post Voucher</button></div></form></div></div></div>
    <template id="voucher-line-template"><div class="voucher-line border rounded p-2 mb-2"><div class="row g-2"><div class="col-md-5"><select data-field="ledger_account_id" class="form-select" required><option value="">Select account</option>@foreach($accounts as $account)<option value="{{ $account->id }}">{{ $account->code }} — {{ $account->name }}</option>@endforeach</select></div><div class="col-md-3"><input data-field="debit" type="number" step="0.01" min="0" value="0" class="form-control voucher-debit" aria-label="Debit"></div><div class="col-md-3"><input data-field="credit" type="number" step="0.01" min="0" value="0" class="form-control voucher-credit" aria-label="Credit"></div><div class="col-md-1"><button type="button" class="btn btn-soft-danger remove-voucher-line"><i class="ri-delete-bin-line"></i></button></div></div></div></template>
</div>
@endsection
@push('scripts')<script src="{{ asset('backend/assets/js/modules/vouchers.js') }}?v={{ filemtime(public_path('backend/assets/js/modules/vouchers.js')) }}"></script>@endpush
