@extends('backend.layouts.app')
@section('title', 'Products | Cholavin ERP')
@section('content')
<div id="products-module" data-index-url="{{ route('admin.products.index') }}" data-pdf-url="{{ route('admin.products.pdf') }}">
    <div class="card erp-panel mb-3"><div class="card-body d-flex justify-content-between align-items-center gap-3"><div><span class="erp-eyebrow">Product masters</span><h4 class="mb-0">Products</h4></div><div>@can('products.export')<button id="products-pdf" class="btn btn-secondary" type="button"><i class="ri-file-pdf-2-line me-1"></i>PDF</button>@endcan @can('create', App\Models\Product::class)<a href="{{ route('admin.products.create') }}" class="btn btn-primary"><i class="ri-add-line me-1"></i>Add Product</a>@endcan</div></div></div>
    <div class="row g-3 mb-3"><div class="col-md-4"><div class="card erp-stat-card"><div><small>Total products</small><strong>{{ $metrics['total'] }}</strong></div></div></div><div class="col-md-4"><div class="card erp-stat-card"><div><small>Active</small><strong>{{ $metrics['active'] }}</strong></div></div></div><div class="col-md-4"><div class="card erp-stat-card"><div><small>Homepage</small><strong>{{ $metrics['homepage'] }}</strong></div></div></div></div>
    <div class="accordion mb-3" id="product-filter-accordion"><div class="accordion-item erp-panel"><h2 class="accordion-header"><button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#product-filter-panel"><i class="ri-filter-3-line me-2"></i>Filters</button></h2><div id="product-filter-panel" class="accordion-collapse collapse"><div class="accordion-body"><form id="product-filters" class="row g-3"><div class="col-lg-4"><label class="form-label" for="product-search">Search</label><input id="product-search" type="search" class="form-control" placeholder="Product or SKU"></div><div class="col-lg-3"><label class="form-label" for="product-category-filter">Category</label><select id="product-category-filter" class="form-select"><option value="">All</option>@foreach($categories as $category)<option value="{{ $category->id }}">{{ $category->name }}</option>@endforeach</select></div><div class="col-lg-2"><label class="form-label" for="product-status-filter">Status</label><select id="product-status-filter" class="form-select"><option value="">All</option><option value="1">Active</option><option value="0">Inactive</option></select></div><div class="col-lg-2"><label class="form-label" for="product-homepage-filter">Homepage</label><select id="product-homepage-filter" class="form-select"><option value="">All</option><option value="1">Shown</option><option value="0">Hidden</option></select></div><div class="col-lg-1 align-self-end"><button id="reset-product-filters" class="btn btn-secondary w-100" type="button"><i class="ri-refresh-line"></i></button></div></form></div></div></div></div>
    <div class="card erp-panel"><div class="card-body table-responsive"><table id="products-table" class="table table-hover align-middle w-100"><thead><tr><th>S.No</th><th>Image</th><th>Name</th><th>Price</th><th>Unit</th><th>Status</th><th>Homepage</th><th>Sort</th><th>Action</th></tr></thead></table></div></div>
</div>
@endsection
@push('scripts')<script src="{{ asset('backend/assets/js/modules/products-index.js') }}?v={{ filemtime(public_path('backend/assets/js/modules/products-index.js')) }}"></script>@endpush
