<?php

return [
    'company' => [
        'name' => 'Cholavin ERP',
        'tagline' => 'Rice Business Solution',
        'brand' => '#800020',
        'deep' => '#4A0012',
        'gold' => '#D4AF37',
    ],

    'common_settings' => [
        'company_name' => 'Cholavin',
        'brand_logo' => 'frontend/assets/img/logo/logo-hm62.png',
        'auth_brand_image' => 'frontend/assets/img/logo/logo-hm64.png',
        'contact_phone' => '+91 99652 52555',
        'whatsapp_number' => '919965252555',
        'company_address' => 'Pallipalayam & Kumarapalayam',
        'facebook' => '#',
        'instagram' => '#',
    ],

    'modules' => [
        'dashboard' => [
            'number' => '01', 'title' => 'Dashboard', 'group' => 'Overview',
            'icon' => 'ri-dashboard-3-line',
            'description' => 'Analytical overview of your entire business.',
            'tabs' => ['Overview', 'Sales', 'Purchase', 'Inventory', 'Outstanding', 'Activity'],
            'kpis' => ['Today\'s Sales', 'Today\'s Purchase', 'Today\'s Collection', 'Gross Profit', 'Stock Value'],
        ],
        'login-authentication' => [
            'number' => '02', 'title' => 'Login & Authentication', 'group' => 'Administration',
            'icon' => 'ri-shield-keyhole-line',
            'description' => 'Secure sign in, recovery, access context, and session controls.',
            'tabs' => ['Login', 'Forgot Password', 'Reset Password', 'OTP / 2FA', 'Device Approval', 'Sessions'],
            'kpis' => ['Active Sessions', 'Login Success', 'Pending Approvals', 'Locked Accounts'],
        ],
        'customer-workspace' => [
            'number' => '03', 'title' => 'Customer Workspace', 'group' => 'Workspaces',
            'icon' => 'ri-user-smile-line',
            'description' => 'Customer profiles, ledger context, and follow-up workspace.',
            'tabs' => ['Overview', 'Sales', 'Payments', 'Returns', 'Outstanding', 'Ledger', 'Delivery', 'Documents', 'Notes', 'Activity'],
            'kpis' => ['Total Customers', 'Active Customers', 'Receivable', 'Overdue'],
        ],
        'supplier-workspace' => [
            'number' => '04', 'title' => 'Supplier Workspace', 'group' => 'Workspaces',
            'icon' => 'ri-truck-line',
            'description' => 'Supplier records, payable context, and purchasing workspace.',
            'tabs' => ['Overview', 'Purchases', 'Payments', 'Returns', 'Outstanding', 'Ledger', 'Items', 'Addresses', 'Documents', 'Notes', 'Activity'],
            'kpis' => ['Total Suppliers', 'Active Suppliers', 'Payable', 'Overdue Payable'],
        ],
        'item-product-master' => [
            'number' => '05', 'title' => 'Item / Product Master', 'group' => 'Master Data',
            'icon' => 'ri-shopping-bag-3-line',
            'description' => 'Rice products, pricing, variants, images, and barcode-ready catalog data.',
            'tabs' => ['Overview', 'Pricing', 'Stock', 'Stock History', 'Purchases', 'Sales', 'Images', 'Barcode', 'Documents', 'Audit'],
            'kpis' => ['Total Items', 'Active Items', 'Low Stock', 'Without Image'],
            'route' => 'admin.products.index',
        ],
        'sales-billing' => [
            'number' => '06', 'title' => 'Sales Billing (New Bill)', 'group' => 'Transactions',
            'icon' => 'ri-bill-line',
            'description' => 'Fast POS workspace with categories, cart, payment, and print flow.',
            'tabs' => ['Categories', 'Product Grid', 'Customer', 'Cart', 'Payment', 'Print'],
            'kpis' => ['Product Search', 'Cart Items', 'Customer Receivable', 'Grand Total'],
        ],
        'sales-invoices' => [
            'number' => '07', 'title' => 'Sales Invoices', 'group' => 'Transactions',
            'icon' => 'ri-file-list-3-line',
            'description' => 'Invoice listing, status tracking, payments, returns, and delivery links.',
            'tabs' => ['Overview', 'Invoice Details', 'Payments', 'Returns', 'Delivery', 'Activity'],
            'kpis' => ['Today Invoices', 'Paid', 'Partial', 'Due', 'Overdue Amount'],
        ],
        'purchase-management' => [
            'number' => '08', 'title' => 'Purchase Management', 'group' => 'Transactions',
            'icon' => 'ri-shopping-cart-2-line',
            'description' => 'Purchase entry and listing shell ready for supplier and receiving workflows.',
            'tabs' => ['Purchase Entry', 'Purchase Listing', 'Payments', 'Returns', 'Attachments', 'Activity'],
            'kpis' => ['Today Purchases', 'Purchase Amount', 'Supplier Payable', 'Pending'],
        ],
        'stock-transfer' => [
            'number' => '09', 'title' => 'Stock Transfer', 'group' => 'Inventory',
            'icon' => 'ri-arrow-left-right-line',
            'description' => 'Godown and shop transfer workflow with approval and receipt stages.',
            'tabs' => ['Request', 'Approval', 'Dispatch', 'In Transit', 'Receipt', 'History'],
            'kpis' => ['Total Transfers', 'Pending Approval', 'Dispatched', 'Awaiting Receipt'],
        ],
        'inventory-stock' => [
            'number' => '10', 'title' => 'Inventory / Stock', 'group' => 'Inventory',
            'icon' => 'ri-stack-line',
            'description' => 'Live stock overview shell for godown, shop, low-stock, and history views.',
            'tabs' => ['Stock Overview', 'Godown Stock', 'Shop Stock', 'Low Stock', 'Damaged Stock', 'History'],
            'kpis' => ['Total Items', 'Total Quantity', 'Stock Value', 'Low Stock', 'Out of Stock'],
        ],
        'party-ledger' => [
            'number' => '11', 'title' => 'Party Ledger', 'group' => 'Accounting',
            'icon' => 'ri-booklet-line',
            'description' => 'Customer and supplier ledger shell with drill-down and statements.',
            'tabs' => ['Customer Ledger', 'Supplier Ledger', 'Transaction Detail', 'Statement', 'Activity'],
            'kpis' => ['Opening Balance', 'Debit', 'Credit', 'Closing Balance', 'Due'],
        ],
        'payment-collection' => [
            'number' => '12', 'title' => 'Payment Collection', 'group' => 'Accounting',
            'icon' => 'ri-hand-coin-line',
            'description' => 'Receipt and payment collection shell with allocation and print steps.',
            'tabs' => ['Payment Form', 'Invoice Allocation', 'Receipt', 'History'],
            'kpis' => ['Current Balance', 'Amount', 'Allocated', 'Unallocated', 'New Balance'],
        ],
        'delivery-management' => [
            'number' => '13', 'title' => 'Delivery Management', 'group' => 'Operations',
            'icon' => 'ri-route-line',
            'description' => 'Delivery assignment, tracking, driver, timeline, and proof-of-delivery shell.',
            'tabs' => ['Overview', 'Items', 'Address', 'Driver', 'Timeline', 'POD', 'Notes', 'Activity'],
            'kpis' => ['Pending', 'Out for Delivery', 'Delivered', 'Failed', 'Rescheduled'],
        ],
        'reports-analytics' => [
            'number' => '14', 'title' => 'Reports & Analytics', 'group' => 'Reports',
            'icon' => 'ri-bar-chart-box-line',
            'description' => 'Report categories, comparisons, drill-down, export, and print surfaces.',
            'tabs' => ['Sales', 'Purchase', 'Inventory', 'Profit', 'Outstanding', 'Payable', 'GST', 'Audit'],
            'kpis' => ['KPI Summary', 'Charts', 'Comparison', 'DataTable'],
        ],
        'financial-dashboard' => [
            'number' => '15', 'title' => 'Financial Dashboard', 'group' => 'Reports',
            'icon' => 'ri-line-chart-line',
            'description' => 'Cash flow, receivables, payables, profit, and expense overview shell.',
            'tabs' => ['Overview', 'Cash Flow', 'Receivables', 'Payables', 'Profit', 'Expenses'],
            'kpis' => ['Cash in Hand', 'Bank Balance', 'Receivable', 'Payable', 'Net Profit'],
        ],
        'users-roles' => [
            'number' => '16', 'title' => 'Users & Role Management', 'group' => 'Administration',
            'icon' => 'ri-user-settings-line',
            'description' => 'User, role, permission matrix, location access, login and activity surfaces.',
            'tabs' => ['Users', 'Roles', 'Permissions', 'Access Control', 'Login Logs', 'Activity Logs'],
            'kpis' => ['Total Users', 'Active Users', 'Roles', 'Restricted Users'],
        ],
        'godown-shop-management' => [
            'number' => '17', 'title' => 'Godown & Shop Management', 'group' => 'Administration',
            'icon' => 'ri-building-2-line',
            'description' => 'Company → Godown → Shop hierarchy and access assignment shell.',
            'tabs' => ['Godowns', 'Shops', 'Stock', 'Transfers', 'Users', 'Reports', 'Activity'],
            'kpis' => ['Total Godowns', 'Total Shops', 'Active Locations', 'Inactive Locations'],
        ],
        'settings-configuration' => [
            'number' => '18', 'title' => 'Settings & Configuration', 'group' => 'Administration',
            'icon' => 'ri-settings-4-line',
            'description' => 'Business, tax, invoice, printer, messaging, financial-year, and security settings.',
            'tabs' => ['Business', 'Tax', 'Invoice', 'Number Series', 'Payments', 'Printer', 'Messaging', 'Financial Year', 'Backup', 'Security', 'Theme'],
            'kpis' => ['Configuration Status', 'Last Updated', 'Integration Health', 'Backup Status'],
        ],
    ],
];
