<?php

return [
    'reference' => [
        'financial-years' => ['title' => 'Financial Years', 'type' => 'financial_year', 'group' => 'Organization'],
        'invoice-sequences' => ['title' => 'Invoice Sequences', 'type' => 'invoice_sequence', 'group' => 'Organization', 'shop_scoped' => true],
        'tax-configurations' => ['title' => 'Tax Configuration', 'type' => 'tax_configuration', 'group' => 'Organization'],
        'bank-accounts' => ['title' => 'Bank Accounts', 'type' => 'bank_account', 'group' => 'Organization', 'shop_scoped' => true],
        'payment-methods' => ['title' => 'Payment Methods', 'type' => 'payment_method', 'group' => 'Organization'],
        'categories' => ['title' => 'Categories', 'type' => 'category', 'group' => 'Product Masters'],
        'subcategories' => ['title' => 'Subcategories', 'type' => 'subcategory', 'parent_type' => 'category', 'group' => 'Product Masters'],
        'brands' => ['title' => 'Brands', 'type' => 'brand', 'group' => 'Product Masters'],
        'units' => ['title' => 'Units', 'type' => 'unit', 'group' => 'Product Masters'],
        'variants' => ['title' => 'Variants', 'type' => 'variant', 'group' => 'Product Masters'],
        'grades' => ['title' => 'Grades', 'type' => 'grade', 'group' => 'Product Masters'],
        'price-lists' => ['title' => 'Price Lists', 'type' => 'price_list', 'group' => 'Product Masters'],
        'tax-rates' => ['title' => 'Tax Rates', 'type' => 'tax_rate', 'group' => 'Product Masters', 'percentage' => true],
        'hsn-sac-codes' => ['title' => 'HSN / SAC Codes', 'type' => 'hsn_sac', 'group' => 'Product Masters', 'percentage' => true],
        'customer-groups' => ['title' => 'Customer Groups', 'type' => 'customer_group', 'group' => 'Party Management'],
        'supplier-groups' => ['title' => 'Supplier Groups', 'type' => 'supplier_group', 'group' => 'Party Management'],
        'vehicles' => ['title' => 'Vehicles', 'type' => 'vehicle', 'group' => 'Delivery'],
        'drivers' => ['title' => 'Drivers', 'type' => 'driver', 'group' => 'Delivery'],
        'delivery-routes' => ['title' => 'Delivery Routes', 'type' => 'delivery_route', 'group' => 'Delivery'],
        'invoice-templates' => ['title' => 'Invoice Templates', 'type' => 'invoice_template', 'group' => 'Settings'],
        'number-sequences' => ['title' => 'Number Sequences', 'type' => 'number_sequence', 'group' => 'Settings', 'shop_scoped' => true],
        'notification-templates' => ['title' => 'Notification Templates', 'type' => 'notification_template', 'group' => 'Notifications'],
    ],
    'documents' => [
        'sales-quotations' => ['title' => 'Sales Quotations', 'type' => 'sales_quotation', 'party_type' => 'customer', 'stock_effect' => 0, 'group' => 'Sales'],
        'sales-orders' => ['title' => 'Sales Orders', 'type' => 'sales_order', 'party_type' => 'customer', 'stock_effect' => 0, 'group' => 'Sales'],
        'delivery-challans' => ['title' => 'Delivery Challans', 'type' => 'delivery_challan', 'party_type' => 'customer', 'stock_effect' => -1, 'group' => 'Sales'],
        'sales-invoices' => ['title' => 'Sales Invoices', 'type' => 'sales_invoice', 'party_type' => 'customer', 'stock_effect' => -1, 'group' => 'Sales'],
        'pos-billing' => ['title' => 'POS Billing', 'type' => 'pos_invoice', 'party_type' => 'customer', 'stock_effect' => -1, 'group' => 'Sales'],
        'sales-returns' => ['title' => 'Sales Returns', 'type' => 'sales_return', 'party_type' => 'customer', 'stock_effect' => 1, 'group' => 'Sales'],
        'credit-notes' => ['title' => 'Credit Notes', 'type' => 'credit_note', 'party_type' => 'customer', 'stock_effect' => 0, 'group' => 'Sales'],
        'purchase-orders' => ['title' => 'Purchase Orders', 'type' => 'purchase_order', 'party_type' => 'supplier', 'stock_effect' => 0, 'group' => 'Purchases'],
        'goods-receipts' => ['title' => 'Goods Receipts', 'type' => 'goods_receipt', 'party_type' => 'supplier', 'stock_effect' => 1, 'group' => 'Purchases'],
        'purchase-bills' => ['title' => 'Purchase Bills', 'type' => 'purchase_bill', 'party_type' => 'supplier', 'stock_effect' => 1, 'group' => 'Purchases'],
        'purchase-returns' => ['title' => 'Purchase Returns', 'type' => 'purchase_return', 'party_type' => 'supplier', 'stock_effect' => -1, 'group' => 'Purchases'],
        'debit-notes' => ['title' => 'Debit Notes', 'type' => 'debit_note', 'party_type' => 'supplier', 'stock_effect' => 0, 'group' => 'Purchases'],
        'stock-adjustments' => ['title' => 'Stock Adjustments', 'type' => 'stock_adjustment', 'party_type' => null, 'stock_effect' => 1, 'group' => 'Inventory'],
        'damaged-stock' => ['title' => 'Damaged Stock', 'type' => 'damaged_stock', 'party_type' => null, 'stock_effect' => -1, 'group' => 'Inventory'],
        'expired-stock' => ['title' => 'Expired Stock', 'type' => 'expired_stock', 'party_type' => null, 'stock_effect' => -1, 'group' => 'Inventory'],
    ],
];
