@extends('backend.layouts.app')
@section('title', 'Notifications | Cholavin ERP')
@section('content')
<div id="notifications-module" data-index-url="{{ route('admin.notifications.index') }}" data-generate-url="{{ route('admin.notifications.generate') }}">
    <div class="card erp-panel mb-3"><div class="card-body d-flex justify-content-between align-items-center gap-3"><div><span class="erp-eyebrow">Alerts & Reminders</span><h4 class="mb-0">Notifications</h4></div>@can('notifications.update')<button id="refresh-alerts" class="btn btn-primary" type="button"><i class="ri-refresh-line me-1"></i>Refresh Operational Alerts</button>@endcan</div></div>
    <div class="accordion mb-3" id="notification-filter-accordion"><div class="accordion-item erp-panel"><h2 class="accordion-header"><button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#notification-filter-panel"><i class="ri-filter-3-line me-2"></i>Filters</button></h2><div id="notification-filter-panel" class="accordion-collapse collapse"><div class="accordion-body"><form id="notification-filters" class="row g-3"><div class="col-lg-5"><label class="form-label" for="notification-search">Search</label><input id="notification-search" class="form-control" type="search" placeholder="Title or message"></div><div class="col-lg-3"><label class="form-label" for="notification-type-filter">Alert type</label><select id="notification-type-filter" class="form-select"><option value="">All</option><option value="low_stock">Low stock</option><option value="expiry">Expiry</option><option value="payment_reminder">Payment reminder</option><option value="pending_delivery">Pending delivery</option></select></div><div class="col-lg-2"><label class="form-label" for="notification-read-filter">Status</label><select id="notification-read-filter" class="form-select"><option value="">All</option><option value="unread">Unread</option><option value="read">Read</option></select></div><div class="col-lg-2 align-self-end"><button id="reset-notification-filters" class="btn btn-secondary w-100" type="button">Reset</button></div></form></div></div></div></div>
    <div class="card erp-panel"><div class="card-body table-responsive"><table id="notifications-table" class="table table-hover align-middle w-100"><thead><tr><th>S.No</th><th>Type</th><th>Title</th><th>Message</th><th>Status</th><th>Created</th><th>Action</th></tr></thead></table></div></div>
</div>
@endsection
@push('scripts')<script src="{{ asset('backend/assets/js/modules/notifications.js') }}?v={{ filemtime(public_path('backend/assets/js/modules/notifications.js')) }}"></script>@endpush
