@extends('backend.layouts.app')

@section('title', 'Billing Dashboard | Cholavin ERP')

@section('content')
<div class="row"><div class="col-12"><div class="page-title-box d-sm-flex align-items-center justify-content-between"><h4 class="mb-sm-0">Billing Dashboard</h4><div class="page-title-right"><ol class="breadcrumb m-0"><li class="breadcrumb-item"><a href="#">Cholavin ERP</a></li><li class="breadcrumb-item active">Dashboard</li></ol></div></div></div></div>
<div class="row">
    <div class="col-xl-3 col-md-6"><div class="card card-animate"><div class="card-body"><p class="text-uppercase fw-medium text-muted text-truncate mb-0">Today Sales</p><div class="d-flex align-items-end justify-content-between mt-4"><div><h4 class="fs-22 fw-semibold ff-secondary mb-4">Rs. 48,500</h4><span class="text-decoration-underline text-muted">View invoices</span></div><div class="avatar-sm flex-shrink-0"><span class="avatar-title bg-success-subtle rounded fs-3"><i class="bx bx-rupee text-success"></i></span></div></div></div></div></div>
    <div class="col-xl-3 col-md-6"><div class="card card-animate"><div class="card-body"><p class="text-uppercase fw-medium text-muted text-truncate mb-0">Invoices</p><div class="d-flex align-items-end justify-content-between mt-4"><div><h4 class="fs-22 fw-semibold ff-secondary mb-4">128</h4><span class="text-decoration-underline text-muted">Draft and paid</span></div><div class="avatar-sm flex-shrink-0"><span class="avatar-title bg-info-subtle rounded fs-3"><i class="ri-file-list-3-line text-info"></i></span></div></div></div></div></div>
    <div class="col-xl-3 col-md-6"><div class="card card-animate"><div class="card-body"><p class="text-uppercase fw-medium text-muted text-truncate mb-0">Customers</p><div class="d-flex align-items-end justify-content-between mt-4"><div><h4 class="fs-22 fw-semibold ff-secondary mb-4">342</h4><span class="text-decoration-underline text-muted">Active buyers</span></div><div class="avatar-sm flex-shrink-0"><span class="avatar-title bg-warning-subtle rounded fs-3"><i class="ri-user-3-line text-warning"></i></span></div></div></div></div></div>
    <div class="col-xl-3 col-md-6"><div class="card card-animate"><div class="card-body"><p class="text-uppercase fw-medium text-muted text-truncate mb-0">Pending Amount</p><div class="d-flex align-items-end justify-content-between mt-4"><div><h4 class="fs-22 fw-semibold ff-secondary mb-4">Rs. 12,900</h4><span class="text-decoration-underline text-muted">Payment follow-up</span></div><div class="avatar-sm flex-shrink-0"><span class="avatar-title bg-danger-subtle rounded fs-3"><i class="ri-wallet-3-line text-danger"></i></span></div></div></div></div></div>
</div>
<div class="row"><div class="col-xl-8"><div class="card"><div class="card-header align-items-center d-flex"><h4 class="card-title mb-0 flex-grow-1">Recent Invoices</h4><button type="button" class="btn btn-soft-primary btn-sm"><i class="ri-add-line align-middle me-1"></i> New Invoice</button></div><div class="card-body"><div class="table-responsive table-card"><table class="table table-hover table-centered align-middle table-nowrap mb-0"><thead class="text-muted table-light"><tr><th>Invoice</th><th>Customer</th><th>Date</th><th>Status</th><th class="text-end">Amount</th></tr></thead><tbody><tr><td><span class="fw-medium">#INV-1001</span></td><td>Kumar Stores</td><td>10 Jul 2026</td><td><span class="badge bg-success-subtle text-success">Paid</span></td><td class="text-end">Rs. 8,400</td></tr><tr><td><span class="fw-medium">#INV-1002</span></td><td>Sri Amman Hotel</td><td>10 Jul 2026</td><td><span class="badge bg-warning-subtle text-warning">Pending</span></td><td class="text-end">Rs. 4,500</td></tr><tr><td><span class="fw-medium">#INV-1003</span></td><td>Home Delivery</td><td>09 Jul 2026</td><td><span class="badge bg-info-subtle text-info">Draft</span></td><td class="text-end">Rs. 2,150</td></tr></tbody></table></div></div></div></div><div class="col-xl-4"><div class="card"><div class="card-header"><h4 class="card-title mb-0">Quick Billing</h4></div><div class="card-body"><div class="mb-3"><label class="form-label">Customer</label><input type="text" class="form-control" placeholder="Select customer"></div><div class="mb-3"><label class="form-label">Product</label><select class="form-select"><option>Premium Rice 25kg</option><option>Biriyani Rice 25kg</option><option>Daily Rice 10kg</option></select></div><div class="row"><div class="col-6 mb-3"><label class="form-label">Qty</label><input type="number" class="form-control" value="1"></div><div class="col-6 mb-3"><label class="form-label">Rate</label><input type="text" class="form-control" value="2100"></div></div><button class="btn btn-primary w-100" type="button"><i class="ri-file-add-line align-middle me-1"></i> Create Invoice UI</button></div></div></div></div>
@endsection
